### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by Daniel-Mietchen** [petermr/openVirus#14]
perhaps separately for
- software
- data
- text
- images and other media derived from the above

**Comment by TS404** [comment]
Agree. What are people's thoughts on ideal licenses?

For data obviously CC0

My default for most text, research and outputs is usually CC BY 4, but I'm happy to go with others' preferences if they want more open than that. What are the most appropriate options for the software license?

**Comment by Daniel-Mietchen** [comment]
I think CC0/Public Domain for everything is the simplest and most reusable approach.

**Comment by TS404** [comment]
I'm happy to support that if @petermr consents.

**Comment by TS404** [comment]
I put in a pull request and merged to master after conversation yesterday with pmr. Contibutors are generally pro public domain code.
