### ISSUE TITLE
dataframe/tibble to quickstatements

### ISSUE THREAD

**Issue by TS404** [petermr/openVirus#17]
A simple solution for export from [R] to wikidata would be to go via [quickstatements](https://tools.wmflabs.org/quickstatements/#/batch). 

1. This could initially be done by formatting up a quickstatements "v1" forat or csv.
2. Eventually this may be achievable via the [quickstatments API](https://tools.wmflabs.org/quickstatements/api.php)

First raised at [this discussion](https://www.wikidata.org/wiki/Wikidata_talk:WikiProject_COVID-19#Mining_COVID19_research_using_%5BR%5D_and_Wikidata)

**Comment by TS404** [comment]
I'm going to make a start on subtask 1 as it seems quite achievable and will probably be a requirement for subtask 2 anyway.

**Comment by magnusmanske** [comment]
The QS API and its token system are detailed [here](https://tools.wmflabs.org/quickstatements/#/user) (if you are logged into QS)

**Comment by TS404** [comment]
A basic [R] function to write quickstatements to tibbles and to V1 format is now working in ([wikiPackageTesting.R](https://github.com/petermr/openVirus/blob/master/wikiPackageTesting.R)). I'll keep track of the next steps in expanding its capabilities over at [I-15](https://github.com/petermr/openVirus/issues/15).
