### ISSUE TITLE
Problem installing ami3 

### ISSUE THREAD

**Issue by Pruthivrajan** [petermr/openVirus#68]
Could not able to run ami3.
command given :ami --help. I am suppose to get dictionaries but facing this:
C:\Users\admin>cd ami3
C:\Users\admin\ami3>ami --help
'ami' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Priya-Jk-15** [comment]
Please check the pre-required installations (Java, JDK, maven and git) and ensure that you have cloned ami3 repository into your system.

Please give a detailed information of the issue, so it will be easier to identify and rectify it.
