### ISSUE TITLE
Git Desktop: fatal: the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by AmbrineH** [petermr/openVirus#74]
I am trying to upload my directory of 950 papers that I downloaded for my mini project. Since the number of files is quite large, I used git desktop for pushing the files to the origin (openVirus Github). Although the files appear to be uploading, I keep getting this error at the end and the directory is still not available on the web. Do I require some additional permissions to accomplish this task?

> Enumerating objects: 3600, done.                                                
> Counting objects: 100% (3600/3600), done.                                       
> Delta compression using up to 12 threads
> Compressing objects: 100% (3590/3590), done.                                    
> error: RPC failed; curl 56 Send failure: Connection was reset                   
> fatal: the remote end hung up unexpectedlyMiB | 58.00 KiB/s                     
> Writing objects: 100% (3596/3596), 654.00 MiB | 124.00 KiB/s, done.             
> Total 3596 (delta 1067), reused 34 (delta 4)
> fatal: the remote end hung up unexpectedly
> Everything up-to-date

**Comment by petermr** [comment]
This often means that the connection is unstable.
It may be useful to reduce the size of the repository and try again.

**Comment by petermr** [comment]
Closed as probably no longer current
