### ISSUE TITLE
ami search

### ISSUE THREAD

**Issue by Pruthivrajan** [petermr/openVirus#75]
I ran this cmd for ami search on 250 corpus article of "viral  epidemic"
`C:\Users\admin>ami -p viralepi1 search --dictionary drug`
where my output should be tabulated with drugs and their frequency. Where as my output was: [file:///C:/Users/admin/viralepi1/commonest.dataTables.html ](url)

**Comment by petermr** [comment]
Thank you.
It should be `drugs`.
This is a bug. And I am working on trying to check for it.
Sorry!

**Comment by Pruthivrajan** [comment]
Thanks it works :)
