### ISSUE TITLE
Unable to install getpapers

### ISSUE THREAD

**Issue by ShweataNHegde** [petermr/openVirus#83]
Following commands were used for the installation. The following were the errors that showed up:
`C:\Users\shweata>npm install --global getpapers`
```
npm ERR! Windows_NT 10.0.18363
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "getpapers"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\shweata\AppData\Roaming\npm-cache\_logs\2020-09-08T12_26_58_379Z-debug.log`
```

**Comment by petermr** [comment]
I searched for the error on Google and got a Stackoverflow question that looks similar:
https://stackoverflow.com/questions/41158164/npm-err-cannot-read-property-path-of-null

**Comment by ShweataNHegde** [comment]
This issue has now been resolved. I will be documenting the installation process shortly.
